/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'any' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface JobApplication {
  'additionalInfo' : [] | [string],
  'applicantName' : string,
  'agreementAccepted' : boolean,
  'preferredTiming' : TimePreference,
  'expectedSalary' : bigint,
  'availableFromDate' : string,
  'dateOfBirth' : string,
  'submissionTimestamp' : Time,
  'jobId' : bigint,
  'resumeFileId' : [] | [bigint],
  'address' : string,
  'gender' : Gender,
  'phoneNumber' : string,
}
export interface JobListing {
  'id' : bigint,
  'title' : string,
  'salary' : SalaryRange,
  'postedDate' : Time,
  'description' : string,
  'distance' : bigint,
  'shift' : Shift,
  'company' : string,
  'genderPreference' : Gender,
  'contactNumber' : [] | [string],
  'requirements' : string,
  'location' : string,
}
export interface SalaryRange { 'max' : bigint, 'min' : bigint }
export type Shift = { 'day' : null } |
  { 'night' : null } |
  { 'flexibleShifts' : null };
export type Time = bigint;
export type TimePreference = { 'day' : null } |
  { 'night' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJobListing' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      Shift,
      Gender,
      string,
      string,
      [] | [string],
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllJobListings' : ActorMethod<[], Array<JobListing>>,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobListingsByDistance' : ActorMethod<[bigint], Array<JobListing>>,
  'getJobListingsByLocation' : ActorMethod<[string], Array<JobListing>>,
  'getJobListingsByPostedDate' : ActorMethod<[Time], Array<JobListing>>,
  'getJobListingsBySalaryRange' : ActorMethod<
    [bigint, bigint],
    Array<JobListing>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Gender,
      TimePreference,
      string,
      bigint,
      bigint,
      boolean,
      [] | [bigint],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];