/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Shift = IDL.Variant({
  'day' : IDL.Null,
  'night' : IDL.Null,
  'flexibleShifts' : IDL.Null,
});
export const Gender = IDL.Variant({
  'any' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SalaryRange = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
export const Time = IDL.Int;
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'salary' : SalaryRange,
  'postedDate' : Time,
  'description' : IDL.Text,
  'distance' : IDL.Nat,
  'shift' : Shift,
  'company' : IDL.Text,
  'genderPreference' : Gender,
  'contactNumber' : IDL.Opt(IDL.Text),
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const TimePreference = IDL.Variant({
  'day' : IDL.Null,
  'night' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'additionalInfo' : IDL.Opt(IDL.Text),
  'applicantName' : IDL.Text,
  'agreementAccepted' : IDL.Bool,
  'preferredTiming' : TimePreference,
  'expectedSalary' : IDL.Nat,
  'availableFromDate' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'submissionTimestamp' : Time,
  'jobId' : IDL.Nat,
  'resumeFileId' : IDL.Opt(IDL.Nat),
  'address' : IDL.Text,
  'gender' : Gender,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        Shift,
        Gender,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobListingsByDistance' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getJobListingsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getJobListingsByPostedDate' : IDL.Func(
      [Time],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getJobListingsBySalaryRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Gender,
        TimePreference,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Shift = IDL.Variant({
    'day' : IDL.Null,
    'night' : IDL.Null,
    'flexibleShifts' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'any' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SalaryRange = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
  const Time = IDL.Int;
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'salary' : SalaryRange,
    'postedDate' : Time,
    'description' : IDL.Text,
    'distance' : IDL.Nat,
    'shift' : Shift,
    'company' : IDL.Text,
    'genderPreference' : Gender,
    'contactNumber' : IDL.Opt(IDL.Text),
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const TimePreference = IDL.Variant({ 'day' : IDL.Null, 'night' : IDL.Null });
  const JobApplication = IDL.Record({
    'additionalInfo' : IDL.Opt(IDL.Text),
    'applicantName' : IDL.Text,
    'agreementAccepted' : IDL.Bool,
    'preferredTiming' : TimePreference,
    'expectedSalary' : IDL.Nat,
    'availableFromDate' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'submissionTimestamp' : Time,
    'jobId' : IDL.Nat,
    'resumeFileId' : IDL.Opt(IDL.Nat),
    'address' : IDL.Text,
    'gender' : Gender,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          Shift,
          Gender,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobListingsByDistance' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getJobListingsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getJobListingsByPostedDate' : IDL.Func(
        [Time],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getJobListingsBySalaryRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Gender,
          TimePreference,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };