/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface JobListing {
    id: bigint;
    title: string;
    salary: SalaryRange;
    postedDate: Time;
    description: string;
    distance: bigint;
    shift: Shift;
    company: string;
    genderPreference: Gender;
    contactNumber?: string;
    requirements: string;
    location: string;
}
export interface JobApplication {
    additionalInfo?: string;
    applicantName: string;
    agreementAccepted: boolean;
    preferredTiming: TimePreference;
    expectedSalary: bigint;
    availableFromDate: string;
    dateOfBirth: string;
    submissionTimestamp: Time;
    jobId: bigint;
    resumeFileId?: bigint;
    address: string;
    gender: Gender;
    phoneNumber: string;
}
export interface UserProfile {
    name: string;
    email?: string;
    phoneNumber?: string;
}
export interface SalaryRange {
    max: bigint;
    min: bigint;
}
export enum Gender {
    any_ = "any",
    female = "female",
    male = "male"
}
export enum Shift {
    day = "day",
    night = "night",
    flexibleShifts = "flexibleShifts"
}
export enum TimePreference {
    day = "day",
    night = "night"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addJobListing(title: string, company: string, location: string, distance: bigint, minSalary: bigint, maxSalary: bigint, shift: Shift, genderPreference: Gender, description: string, requirements: string, contactNumber: string | null): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllJobListings(): Promise<Array<JobListing>>;
    getApplicationsForJob(jobId: bigint): Promise<Array<JobApplication>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobListingsByDistance(maxDistance: bigint): Promise<Array<JobListing>>;
    getJobListingsByLocation(location: string): Promise<Array<JobListing>>;
    getJobListingsByPostedDate(arg0: Time): Promise<Array<JobListing>>;
    getJobListingsBySalaryRange(minSalary: bigint, maxSalary: bigint): Promise<Array<JobListing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitApplication(applicantName: string, dateOfBirth: string, phoneNumber: string, address: string, gender: Gender, preferredTiming: TimePreference, availableFromDate: string, expectedSalary: bigint, jobId: bigint, agreementAccepted: boolean, resumeFileId: bigint | null, additionalInfo: string | null): Promise<void>;
}
import type { Gender as _Gender, JobApplication as _JobApplication, JobListing as _JobListing, SalaryRange as _SalaryRange, Shift as _Shift, Time as _Time, TimePreference as _TimePreference, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addJobListing(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: Shift, arg7: Gender, arg8: string, arg9: string, arg10: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJobListing(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Shift_n1(this._uploadFile, this._downloadFile, arg6), to_candid_Gender_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJobListing(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Shift_n1(this._uploadFile, this._downloadFile, arg6), to_candid_Gender_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobListings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobListings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationsForJob(arg0: bigint): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForJob(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForJob(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListingsByDistance(arg0: bigint): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListingsByDistance(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListingsByDistance(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListingsByLocation(arg0: string): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListingsByLocation(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListingsByLocation(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListingsByPostedDate(arg0: Time): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListingsByPostedDate(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListingsByPostedDate(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListingsBySalaryRange(arg0: bigint, arg1: bigint): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListingsBySalaryRange(arg0, arg1);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListingsBySalaryRange(arg0, arg1);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitApplication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Gender, arg5: TimePreference, arg6: string, arg7: bigint, arg8: bigint, arg9: boolean, arg10: bigint | null, arg11: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, to_candid_Gender_n3(this._uploadFile, this._downloadFile, arg4), to_candid_TimePreference_n29(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0, arg1, arg2, arg3, to_candid_Gender_n3(this._uploadFile, this._downloadFile, arg4), to_candid_TimePreference_n29(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
}
function from_candid_Gender_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_JobApplication_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobApplication): JobApplication {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_JobListing_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobListing): JobListing {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Shift_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shift): Shift {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TimePreference_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimePreference): TimePreference {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    salary: _SalaryRange;
    postedDate: _Time;
    description: string;
    distance: bigint;
    shift: _Shift;
    company: string;
    genderPreference: _Gender;
    contactNumber: [] | [string];
    requirements: string;
    location: string;
}): {
    id: bigint;
    title: string;
    salary: SalaryRange;
    postedDate: Time;
    description: string;
    distance: bigint;
    shift: Shift;
    company: string;
    genderPreference: Gender;
    contactNumber?: string;
    requirements: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        salary: value.salary,
        postedDate: value.postedDate,
        description: value.description,
        distance: value.distance,
        shift: from_candid_Shift_n11(_uploadFile, _downloadFile, value.shift),
        company: value.company,
        genderPreference: from_candid_Gender_n13(_uploadFile, _downloadFile, value.genderPreference),
        contactNumber: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.contactNumber)),
        requirements: value.requirements,
        location: value.location
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    additionalInfo: [] | [string];
    applicantName: string;
    agreementAccepted: boolean;
    preferredTiming: _TimePreference;
    expectedSalary: bigint;
    availableFromDate: string;
    dateOfBirth: string;
    submissionTimestamp: _Time;
    jobId: bigint;
    resumeFileId: [] | [bigint];
    address: string;
    gender: _Gender;
    phoneNumber: string;
}): {
    additionalInfo?: string;
    applicantName: string;
    agreementAccepted: boolean;
    preferredTiming: TimePreference;
    expectedSalary: bigint;
    availableFromDate: string;
    dateOfBirth: string;
    submissionTimestamp: Time;
    jobId: bigint;
    resumeFileId?: bigint;
    address: string;
    gender: Gender;
    phoneNumber: string;
} {
    return {
        additionalInfo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.additionalInfo)),
        applicantName: value.applicantName,
        agreementAccepted: value.agreementAccepted,
        preferredTiming: from_candid_TimePreference_n19(_uploadFile, _downloadFile, value.preferredTiming),
        expectedSalary: value.expectedSalary,
        availableFromDate: value.availableFromDate,
        dateOfBirth: value.dateOfBirth,
        submissionTimestamp: value.submissionTimestamp,
        jobId: value.jobId,
        resumeFileId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.resumeFileId)),
        address: value.address,
        gender: from_candid_Gender_n13(_uploadFile, _downloadFile, value.gender),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phoneNumber: [] | [string];
}): {
    name: string;
    email?: string;
    phoneNumber?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.email)),
        phoneNumber: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.phoneNumber))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: null;
} | {
    night: null;
} | {
    flexibleShifts: null;
}): Shift {
    return "day" in value ? Shift.day : "night" in value ? Shift.night : "flexibleShifts" in value ? Shift.flexibleShifts : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    any: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "any" in value ? Gender.any : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: null;
} | {
    night: null;
}): TimePreference {
    return "day" in value ? TimePreference.day : "night" in value ? TimePreference.night : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobApplication>): Array<JobApplication> {
    return value.map((x)=>from_candid_JobApplication_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobListing>): Array<JobListing> {
    return value.map((x)=>from_candid_JobListing_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Shift_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shift): _Shift {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TimePreference_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePreference): _TimePreference {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phoneNumber?: string;
}): {
    name: string;
    email: [] | [string];
    phoneNumber: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shift): {
    day: null;
} | {
    night: null;
} | {
    flexibleShifts: null;
} {
    return value == Shift.day ? {
        day: null
    } : value == Shift.night ? {
        night: null
    } : value == Shift.flexibleShifts ? {
        flexibleShifts: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePreference): {
    day: null;
} | {
    night: null;
} {
    return value == TimePreference.day ? {
        day: null
    } : value == TimePreference.night ? {
        night: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    any: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.any ? {
        any_: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
